# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

name: Static analysis

on:
  pull_request:
    paths:
      - '.github/workflows/psalm.yml'
      - 'appinfo/**'
      - 'lib/**'
      - 'templates/**'
      - 'tests/**'
      - '.php-cs-fixer.dist.php'
      - 'psalm.xml'
      - 'composer.json'
      - 'composer.lock'
      - '**/composer.json'
      - '**/composer.lock'
  push:
    branches:
      - main
      - master
      - stable*

permissions:
  contents: read

concurrency:
  group: psalm-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        server-versions: ['stable28', 'stable29', 'stable30', 'stable31', 'stable32']

    name: Nextcloud ${{ matrix.server-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none

      - name: Install dependencies for Nextcloud ${{ matrix.server-versions }}
        run: |
          sed -i "s|dev-stable28|dev-${{ matrix.server-versions }}|" composer.json
          composer update "nextcloud/ocp" --with-all-dependencies
          composer i

      - name: Run coding standards check
        run: composer run psalm
